-- MySQL Script generated by MySQL Workbench
-- Παρ 02 Απρ 2021 12:00:17 πμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_1` ;
USE `exercise_1` ;

-- -----------------------------------------------------
-- Table `exercise_1`.`Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Center` (
  `Id_Center` INT NOT NULL,
  `VACCIEN` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id_Center`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospital` (
  `Telephone` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Center_Id_Center` INT NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_Hospital_Center1_idx` (`Center_Id_Center` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_Center1`
    FOREIGN KEY (`Center_Id_Center`)
    REFERENCES `exercise_1`.`Center` (`Id_Center`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Doctor` (
  `Telephone` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  `Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_Telephone`)
    REFERENCES `exercise_1`.`Hospital` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Patient` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Telephone` INT NOT NULL,
  `History` TEXT(1000) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`EODY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`EODY` (
  `Id-test` INT NOT NULL,
  PRIMARY KEY (`Id-test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Visited`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Visited` (
  `Num_Visited_Patient` INT NOT NULL,
  `Patient_email` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Doctor_Telephone` INT NOT NULL,
  `Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`Num_Visited_Patient`, `Patient_email`, `Hospital_Telephone`),
  INDEX `fk_Visited_Patient1_idx` (`Patient_email` ASC) VISIBLE,
  INDEX `fk_Visited_Hospital1_idx` (`Hospital_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Visited_Patient1`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_Hospital1`
    FOREIGN KEY (`Hospital_Telephone`)
    REFERENCES `exercise_1`.`Hospital` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Test` (
  `Type` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `Supect_Email` TEXT(1000) NULL,
  `EODY_Id-test` INT NOT NULL,
  `Visited_Num_Visited_Patient` INT NOT NULL,
  `Visited_Patient_email` VARCHAR(45) NOT NULL,
  `Visited_Hospital_Telephone` INT NOT NULL,
  INDEX `fk_Test_EODY1_idx` (`EODY_Id-test` ASC) VISIBLE,
  PRIMARY KEY (`Visited_Num_Visited_Patient`, `Visited_Patient_email`, `Visited_Hospital_Telephone`),
  CONSTRAINT `fk_Test_EODY1`
    FOREIGN KEY (`EODY_Id-test`)
    REFERENCES `exercise_1`.`EODY` (`Id-test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Visited1`
    FOREIGN KEY (`Visited_Num_Visited_Patient` , `Visited_Patient_email` , `Visited_Hospital_Telephone`)
    REFERENCES `exercise_1`.`Visited` (`Num_Visited_Patient` , `Patient_email` , `Hospital_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospitalization` (
  `Symptoms` TEXT(150) NULL,
  `hospitalization` TINYINT(1) NOT NULL,
  `Treatment` TEXT(200) NULL,
  `Test_Visited_Num_Visited_Patient` INT NOT NULL,
  `Test_Visited_Patient_email` VARCHAR(45) NOT NULL,
  `Test_Visited_Hospital_Telephone` INT NOT NULL,
  `Room_id` INT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NULL,
  PRIMARY KEY (`Test_Visited_Num_Visited_Patient`, `Test_Visited_Patient_email`, `Test_Visited_Hospital_Telephone`),
  CONSTRAINT `fk_Hospitalization_Test1`
    FOREIGN KEY (`Test_Visited_Num_Visited_Patient` , `Test_Visited_Patient_email` , `Test_Visited_Hospital_Telephone`)
    REFERENCES `exercise_1`.`Test` (`Visited_Num_Visited_Patient` , `Visited_Patient_email` , `Visited_Hospital_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HospitalWard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HospitalWard` (
  `Id_Ward` VARCHAR(45) NOT NULL,
  `Number_rooms` INT NOT NULL,
  `Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`Id_Ward`, `Hospital_Telephone`),
  INDEX `fk_HospitalWard_Hospital1_idx` (`Hospital_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_HospitalWard_Hospital1`
    FOREIGN KEY (`Hospital_Telephone`)
    REFERENCES `exercise_1`.`Hospital` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Rooms` (
  `Room_id` VARCHAR(45) NOT NULL,
  `Beds` INT NOT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`Room_id`, `HospitalWard_Id_Ward`, `HospitalWard_Hospital_Telephone`),
  INDEX `fk_Rooms_HospitalWard1_idx` (`HospitalWard_Id_Ward` ASC, `HospitalWard_Hospital_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward` , `HospitalWard_Hospital_Telephone`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward` , `Hospital_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`TypeWard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`TypeWard` (
  `Type` VARCHAR(45) NOT NULL,
  `Medical_Specialty` VARCHAR(45) NULL,
  `Num_Bed` INT NULL,
  `Num_Patient` INT NULL,
  `Covid` TINYINT(1) NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`HospitalWard_Id_Ward`, `HospitalWard_Hospital_Telephone`),
  CONSTRAINT `fk_TypeWard_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward` , `HospitalWard_Hospital_Telephone`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward` , `Hospital_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`WorkDay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`WorkDay` (
  `Day` VARCHAR(45) NOT NULL,
  `Doctor_Telephone` INT NOT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_Telephone` INT NOT NULL,
  PRIMARY KEY (`Doctor_Telephone`, `Day`),
  INDEX `fk_WorkDay_HospitalWard1_idx` (`HospitalWard_Id_Ward` ASC, `HospitalWard_Hospital_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_WorkDay_Doctor1`
    FOREIGN KEY (`Doctor_Telephone`)
    REFERENCES `exercise_1`.`Doctor` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkDay_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward` , `HospitalWard_Hospital_Telephone`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward` , `Hospital_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HealthCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HealthCenter` (
  `Telephone` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Center_Id_Center` INT NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_HealthCenter_Center1_idx` (`Center_Id_Center` ASC) VISIBLE,
  CONSTRAINT `fk_HealthCenter_Center1`
    FOREIGN KEY (`Center_Id_Center`)
    REFERENCES `exercise_1`.`Center` (`Id_Center`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Visited_HealthCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Visited_HealthCenter` (
  `Num_Visted_Patient` INT NOT NULL,
  `Patient_email` VARCHAR(45) NOT NULL,
  `HealthCenter_Telephone` INT NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Num_Visted_Patient`, `Patient_email`, `HealthCenter_Telephone`),
  INDEX `fk_Visited_HealthCenter_Patient1_idx` (`Patient_email` ASC) VISIBLE,
  INDEX `fk_Visited_HealthCenter_HealthCenter1_idx` (`HealthCenter_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Visited_HealthCenter_Patient1`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_HealthCenter_HealthCenter1`
    FOREIGN KEY (`HealthCenter_Telephone`)
    REFERENCES `exercise_1`.`HealthCenter` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Test_Health_Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Test_Health_Center` (
  `Type` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `Suspect_Email` TEXT(1000) NULL,
  `Visited_HealthCenter_Num_Visted_Patient` INT NOT NULL,
  `Visited_HealthCenter_Patient_email` VARCHAR(45) NOT NULL,
  `Visited_HealthCenter_HealthCenter_Telephone` INT NOT NULL,
  `EODY_Id-test` INT NOT NULL,
  PRIMARY KEY (`Visited_HealthCenter_Num_Visted_Patient`, `Visited_HealthCenter_Patient_email`, `Visited_HealthCenter_HealthCenter_Telephone`),
  INDEX `fk_Test_Health_Center_EODY1_idx` (`EODY_Id-test` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Health_Center_Visited_HealthCenter1`
    FOREIGN KEY (`Visited_HealthCenter_Num_Visted_Patient` , `Visited_HealthCenter_Patient_email` , `Visited_HealthCenter_HealthCenter_Telephone`)
    REFERENCES `exercise_1`.`Visited_HealthCenter` (`Num_Visted_Patient` , `Patient_email` , `HealthCenter_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Health_Center_EODY1`
    FOREIGN KEY (`EODY_Id-test`)
    REFERENCES `exercise_1`.`EODY` (`Id-test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HDIKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HDIKA` (
  `AMKA` INT NOT NULL,
  `BirthDay` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AMKA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`EMA_Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`EMA_Vaccines` (
  `EMA_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Doses` INT NOT NULL,
  `Approval` TINYINT(1) NOT NULL,
  `Id_Approval` INT NULL,
  `Date_Approval` DATE NULL,
  PRIMARY KEY (`EMA_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`PharmaceuticalCorporation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`PharmaceuticalCorporation` (
  `Telephone` VARCHAR(45) NOT NULL,
  `EMA_Vaccines_EMA_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Technology` VARCHAR(45) NOT NULL,
  `Storage_Conditions` TEXT(750) NOT NULL,
  `Monthly_Production` INT NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_PharmaceuticalCorporation_EMA_Vaccines1_idx` (`EMA_Vaccines_EMA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PharmaceuticalCorporation_EMA_Vaccines1`
    FOREIGN KEY (`EMA_Vaccines_EMA_ID`)
    REFERENCES `exercise_1`.`EMA_Vaccines` (`EMA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`StorageCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`StorageCompanies` (
  `Telephone` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `PharmaceuticalCorporation_Telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_StorageCompanies_PharmaceuticalCorporation1_idx` (`PharmaceuticalCorporation_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_StorageCompanies_PharmaceuticalCorporation1`
    FOREIGN KEY (`PharmaceuticalCorporation_Telephone`)
    REFERENCES `exercise_1`.`PharmaceuticalCorporation` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Batch_Of_Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Batch_Of_Vaccines` (
  `PharmaceuticalCorporation_Telephone` VARCHAR(45) NOT NULL,
  `StorageCompanies_Telephone` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Number` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `VaccinationCenter` TEXT(2000) NOT NULL,
  PRIMARY KEY (`PharmaceuticalCorporation_Telephone`, `StorageCompanies_Telephone`, `Date`, `Number`, `Country`),
  INDEX `fk_Batch_Of_Vaccines_StorageCompanies1_idx` (`StorageCompanies_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Batch_Of_Vaccines_PharmaceuticalCorporation1`
    FOREIGN KEY (`PharmaceuticalCorporation_Telephone`)
    REFERENCES `exercise_1`.`PharmaceuticalCorporation` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Batch_Of_Vaccines_StorageCompanies1`
    FOREIGN KEY (`StorageCompanies_Telephone`)
    REFERENCES `exercise_1`.`StorageCompanies` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Vaccination` (
  `HDIKA_AMKA` INT NOT NULL,
  `Date_Of_Doses` TEXT(500) NOT NULL,
  `Center_Id_Center` INT NOT NULL,
  PRIMARY KEY (`HDIKA_AMKA`),
  INDEX `fk_Vaccination_Center1_idx` (`Center_Id_Center` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccination_HDIKA1`
    FOREIGN KEY (`HDIKA_AMKA`)
    REFERENCES `exercise_1`.`HDIKA` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccination_Center1`
    FOREIGN KEY (`Center_Id_Center`)
    REFERENCES `exercise_1`.`Center` (`Id_Center`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Center_has_Batch_Of_Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Center_has_Batch_Of_Vaccines` (
  `Center_Id_Center` INT NOT NULL,
  `Batch_Of_Vaccines_PharmaceuticalCorporation_Telephone` VARCHAR(45) NOT NULL,
  `Batch_Of_Vaccines_StorageCompanies_Telephone` INT NOT NULL,
  `Batch_Of_Vaccines_Date` DATE NOT NULL,
  `Batch_Of_Vaccines_Number` INT NOT NULL,
  `Batch_Of_Vaccines_Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Center_Id_Center`, `Batch_Of_Vaccines_PharmaceuticalCorporation_Telephone`, `Batch_Of_Vaccines_StorageCompanies_Telephone`, `Batch_Of_Vaccines_Date`, `Batch_Of_Vaccines_Number`, `Batch_Of_Vaccines_Country`),
  INDEX `fk_Center_has_Batch_Of_Vaccines_Batch_Of_Vaccines1_idx` (`Batch_Of_Vaccines_PharmaceuticalCorporation_Telephone` ASC, `Batch_Of_Vaccines_StorageCompanies_Telephone` ASC, `Batch_Of_Vaccines_Date` ASC, `Batch_Of_Vaccines_Number` ASC, `Batch_Of_Vaccines_Country` ASC) VISIBLE,
  INDEX `fk_Center_has_Batch_Of_Vaccines_Center1_idx` (`Center_Id_Center` ASC) VISIBLE,
  CONSTRAINT `fk_Center_has_Batch_Of_Vaccines_Center1`
    FOREIGN KEY (`Center_Id_Center`)
    REFERENCES `exercise_1`.`Center` (`Id_Center`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Center_has_Batch_Of_Vaccines_Batch_Of_Vaccines1`
    FOREIGN KEY (`Batch_Of_Vaccines_PharmaceuticalCorporation_Telephone` , `Batch_Of_Vaccines_StorageCompanies_Telephone` , `Batch_Of_Vaccines_Date` , `Batch_Of_Vaccines_Number` , `Batch_Of_Vaccines_Country`)
    REFERENCES `exercise_1`.`Batch_Of_Vaccines` (`PharmaceuticalCorporation_Telephone` , `StorageCompanies_Telephone` , `Date` , `Number` , `Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
